[container]
# This fixes a weird thing where it says "Systemd"
# at the start of the prompt in WSL.
# https://www.reddit.com/r/fishshell/comments/yhoi28/im_using_starship_prompt_in_wsl_and_it_keep/
disabled = true 