theme = "everforest_dark"

[editor]
auto-pairs = false
line-number = "relative"
mouse = false
rulers = [80]
# For 22.08 and above...
cursorline = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.whitespace]
render = "all"

[keys.normal]
"$" = "goto_line_end"
"0" = "goto_line_start"
"," = { d = "goto_definition"}
";" = "command_mode"

[keys.insert]
j = { k = "normal_mode" }

[keys.select]
"$" = "goto_line_end"
"0" = "goto_line_start"
