theme = "onedark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[keys.normal]
"$" = "goto_line_end"
"0" = "goto_line_start"

[keys.insert]
j = { k = "normal_mode" }
